export const queryKeys = {
	me: () => ["me"] as const,
	tenant: (slug: string) => ["tenant", slug] as const,
	activeConference: (slug: string) => ["active-conference", slug] as const,
	confTheme: (slug: string) => ["conf-theme", slug] as const,
	confThemeLogo: (slug: string, logoFileId: string | null) =>
		["conf-theme-logo", slug, logoFileId] as const,
	appSettings: (slug: string) => ["app-settings", slug] as const,
	customFields: (slug: string, entity: string) => ["custom-fields", slug, entity] as const,
	importJobs: (slug: string) => ["import-jobs", slug] as const,
	importJob: (slug: string, jobId: string) => ["import-job", slug, jobId] as const,
	importRows: (slug: string, jobId: string) => ["import-rows", slug, jobId] as const,
	committees: (slug: string) => ["committees", slug] as const,
	assignments: (slug: string, committeeId?: string | null) =>
		["assignments", slug, committeeId] as const,
	staff: (slug: string) => ["staff", slug] as const,
	staffAll: (slug: string) => ["staff-all", slug] as const,
	vipChecklist: (slug: string, vipId: string) => ["vip-checklist", slug, vipId] as const,
	vip: (slug: string) => ["vip", slug] as const,
	helpdesk: (slug: string) => ["helpdesk", slug] as const,
	dashboard: (slug: string) => ["dashboard", slug] as const,
	foodPlans: (slug: string) => ["food-plans", slug] as const,
	mealScanStats: (slug: string) => ["meal-scan-stats", slug] as const,
	vehicles: (slug: string) => ["vehicles", slug] as const,
	travel: (slug: string) => ["travel", slug] as const,
	sessions: (slug: string) => ["sessions", slug] as const,
	venues: (slug: string) => ["venues", slug] as const,
	tracks: (slug: string) => ["tracks", slug] as const,
	reports: (slug: string) => ["reports", slug] as const,
	certificates: (slug: string) => ["certificates", slug] as const,
	attendeesStats: (slug: string) => ["attendees-stats", slug] as const,
	travelManifest: (slug: string, direction: "arrival" | "departure") =>
		["travel-manifest", slug, direction] as const,
	accommodationAllocations: (slug: string) => ["accommodation-allocations", slug] as const,
	attendees: (slug: string) => ["attendees", slug] as const,
	financeSummary: (slug: string) => ["finance-summary", slug] as const,
	financeItems: (slug: string) => ["finance-items", slug] as const,
	sponsors: (slug: string) => ["sponsors", slug] as const,
	accBlocks: (slug: string) => ["acc-blocks", slug] as const,
	accAllRooms: (slug: string) => ["acc-all-rooms", slug] as const,
	accRooms: (slug: string, blockId?: string | null) => ["acc-rooms", slug, blockId] as const,
	accAllocs: (slug: string, roomId: string) => ["acc-allocs", slug, roomId] as const,
	announcements: (slug: string) => ["announcements", slug] as const,
	providers: (slug: string) => ["providers", slug] as const,
	templates: (slug: string) => ["templates", slug] as const,
	campaigns: (slug: string) => ["campaigns", slug] as const,
	feedback: (slug: string) => ["feedback", slug] as const,
	members: (slug: string) => ["members", slug] as const,
	invites: (slug: string) => ["invites", slug] as const,
	logistics: (slug: string) => ["logistics", slug] as const,
	controlRoomLogs: (slug: string) => ["control-room-logs", slug] as const,
	list<TKey extends readonly unknown[]>(
		key: TKey,
		params?: Record<string, string | number | boolean | undefined | null>,
	) {
		return params ? ([...key, params] as const) : key;
	},
	scoped: (key: string, slug: string) => [key, slug] as const,
	scopedWithId: (key: string, slug: string, id: string) => [key, slug, id] as const,
} as const;
